### ISSUE TITLE
libnvidia-fatbinaryloader.so.375.26

### ISSUE THREAD

**Issue by akorchemniy** [gw0/docker-debian-cuda#1]
My system was complaining about libnvidia-fatbinaryloader.so.375.26. To work around this issue, I added: 

$(ls /usr/lib/x86_64-linux-gnu/libnvidia* | xargs -I{} echo '-v {}:{}:ro')

**Comment by gw0** [comment]
Thank you very much. I have improved the documentation to:

```
$ docker run -it --rm $(ls /dev/nvidia* | xargs -I{} echo '--device={}') $(ls /usr/lib/x86_64-linux-gnu/{libcuda,libnvidia}* | xargs -I{} echo '-v {}:{}:ro') gw000/debian-cuda
```
