### ISSUE TITLE
Possibility of a Buster version?

### ISSUE THREAD

**Issue by dmm** [gw0/docker-debian-cuda#2]
Now that Debian Buster is out, have you considered creating a docker image for that release? If you're not currently working on it I will make an attempt and submit a pull request.

In that line of thinking do you have an idea of what versions of the cuda libraries would most likely be compatible?

Thanks for releasing this useful project!

**Comment by gw0** [comment]
Sorry for the late reply. As you might have noticed, I am currently not working on this. Unfortunately finding compatible Cuda versions is an trail and error process.

Feel free to make a pull request.

**Comment by dmm** [comment]
I'll submit a pull request with what I've been using.
